version: 0.0

os: linux

files:
  - source: target/jenkins.jar
    destination: /home/ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 20
      runas: ec2-user
