version: 0.0

os: linux

files:
  - source: target/jenkins.jar
    destination: /tmp

hooks:
  ApplicationStop:
    - location: stop-process.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: start-process.sh
      timeout: 20
      runas: ec2-user
